[package]
name = "termrock-overlays"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
termrock-core.workspace = true
termrock-layout.workspace = true
termrock-theme.workspace = true
termrock-text.workspace = true
termrock-render.workspace = true
termrock-collections.workspace = true
termrock-runtime.workspace = true
termrock-controls.workspace = true
termrock-fields.workspace = true
termrock-navigation.workspace = true
termrock-viewport.workspace = true
termrock-feedback.workspace = true
unicode-width.workspace = true
ratatui.workspace = true
ratatui-core.workspace = true
