[package]
name = "jackin-preview"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
jackin-preview-app.workspace = true
jackin-preview-sim.workspace = true
termrock.workspace = true
termrock-session.workspace = true
clap.workspace = true
ratatui.workspace = true
