[package]
name = "termrock-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
termrock-core.workspace = true
termrock-theme.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
ratatui.workspace = true
ratatui-core.workspace = true
